target-version = "py312"
line-length = 90

[lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
# Add the `line-too-long` rule to the enforced rule set.
extend-select = ["E501"]

[format]
quote-style = "single"
indent-style = "space"
docstring-code-format = true
docstring-code-line-length = 20
